name: Update Stok JSON

on:
  schedule:
    - cron: "0 * * * *"  # Setiap 1 jam sekali
  workflow_dispatch:     # Bisa dijalankan manual juga dari GitHub UI

jobs:
  update-stok:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Run data fetch script
        run: python scripts/fetch_firebase_to_json.py

      - name: Commit and push if stok.json changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/stok.json
          git diff --cached --quiet || (git commit -m "Update stok.json from Firebase" && git push)